travis:
  secure:
    BINSTAR_TOKEN: vtVxQhVpVteW6z0WBJu9mLhASuC3S11/PJjFNbGfN4Iry22EBMnKzkg+2UdTxzamRhzfBDrmGiro2GM8qMnGnEwI3XF7HcffDhZ08aRmQDKww5tjF+oXMTEz72fqNJQSpOP4G3dwCxWf1SS6Geg9Cx1HBJ3Vcco5GuGSrt3YLeE8vjcZD0JUGXmTNbHRyDYBeRX0UPEXLHGXr5DVAQ4C+wVOW6NYE41sGWhqlM/9ne4OVjR8VUwF9FoU8K9NrxgME5ZTE6LOdnEdxIYlKgHJMW8u4Lnff/raipStllM7jRkgrd2A+eMcBR48zme4uvpBHBTMQD9zdPBkcn2458OukqrNiIwnevn36kn2pCHqy8xrhHsHa/97AT325Y86lQCk/ySI7yAXPC7vwmnPP5UH8ZWmEVIgp4czJoJmKYMmmlS7icBMepJyPKwy4QNJRzychob3gSn0sGXt8T1lQ4hKTH0mMQ2W4FDIYpXPJclyjv/hEt/ZKD1b8V1Uo6cA9fHyH04DDrmMiCexr5+5v8f8nZi1mOdgo62GmIU+jg26J5vCPxCJcj+chmoe2H59/UtfXTatMUUgl1/glQ02NMN1UdQVHD234+Np7ewtif9qkNTD4apEV4SRS2y2xGT/SnbCQQnRTPoCLBleP1OEjclfp8kpxtXkZugZI/eMIe2XpBY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
