travis:
  secure:
    BINSTAR_TOKEN: w6mMXx2f0vdnK7TR8kOWjqE+OW/nRg9WiFI2t0O34EQJxCml5skv0DKcXCgQQa1EnwiX6NtNPd8W1z040EFuxCQMCM80PyNKOtKqget++m4CE8lxKz05m05cMsHYtR8acAQahdQiJatL/4ZgLYWWWkuDtMCfECQaJ3HM8o8uQkS3+WE2mEEyMDP++/C33G3S59x8/7NuZSYHxSY5KWnsaoahPiTg3uLZYIYraFFLJwvP/WlBXF/DyT/RJqhga8R5EmP0Xau0El7GAb+Juu5/dcjQuHKQyyROWBL/ASE2BGNN5ZHLFUfHhqomTGSjzuCU7aojSdeFnEIQRrRkTMx7A9KY2WBur+lLmwm6dX7jkr6Hm4cIldac6rsD2CSkXdPElV07QwY+zXhRJd+tAzSpXVeD9NU7bETJMh00md6TFrAb2Jpd0ZMjLptLcWg7z5k1mIghPwN/NuKku40SGBCIqWf2OfRW5vHd+GSTssflJKbPPqA227sJJpPHyPFn9CBoCxr/BiFWuMRd3/pHR3FUS+cPOs3qAHDsZ+7zJUHsZ56wMs/ZctnTC6KeN+qrb5l8ZqQknEpnwejkCO8Wifo2oRfnTWy/AirjlfvoWkT046+Z9q4l1Uancx5DMTZatv4FbTiFAy0UPX1uEN4LVRiT1+Nomy5rrzmi1HcELf6yGuU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
