travis:
  secure:
    BINSTAR_TOKEN: eb6IaAf8wphrQ1+b0VK8/qYGtLXrxu817f7/Kse4r7AyzWe842Whpc9U3sh5xTt2CuN680Gt0rVaidDr2OVv1qf7XPMjCaGVBAGiN1YsXwVQp22dSzFB5Rx4uQ9VutnVaip0P33VCRN6PCWhnaSzJGhQZYMzZXpI3h5moxOARncbAdyYLUsaYY//VbbQKn6+tn1G5FmgVgvlz0db2bVWQPx1O3M+mA/MJj9qiQVKJtw9B+fkXn1mIhZaiVEmSmmXOnQJijNag0dXGQdd7u3QlYOwnkGWzbsHkOoyhhkFpa1nelbLb4fbBh8HoI61C6XHQtSud9mBF/iEn1Jx0xVcciE/ExVi1wNCPYrAw+bjf/8sfkbUFwieoyzJllh7aq+X8dj7lvnAsrzhXnKR+O1FOK5Id9nIKlg/dM4mBS/s3VR8VDl1QtUVvZj2h4B0HI4+codSWUA89c087625yNL+XGJZAN3zVvCY/XEWTVBXUE5xm+WPOun5VKLTgNKfeLCiaVR5BhEr9TtD8u5eaQqjp1NIYsuKWKWkCKmyu5npDSlZkXhyoqXgo0juVp1NVdgQ/IwTNgDpL1YiWVw//7sia+LxVvl32Wgu/IdoTqS2PXEkxMB2w7kfBPDNj5e4KBNjoCFCjI/qe3Ov4SAkO7vv5hT+I5UbialifzF1Y/mP3h4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
