travis:
  secure:
    BINSTAR_TOKEN: A3qw083C8gM35gpP/JCwuBuRnaKFIRi5Ew+flHGxlMz3KkCpdZnBFS/vfrQDDinjbCJG72RzMoIcUOlHZsZEPVxxRn4+haNUPm9L5pukFW35CUXgV3fV1GLdMigvsBuBYrWNSq1fVT/nA1wSUxLgFbnv/e9JLQgTm9npFjXQZdIM8INQfmrKxgDKC7i4zynZlrYRvRD5QYn+b6RcrYlN1E0hVC3uWGNzvDl40RtUsDpLW194BY163eVOQbZKUPahAPXgloU6JoaIkqB75AUWQn2uUY61guRyn6mC2jqrPbyt58k59jMBL+NG2fZfsO0XlbXuaKhvCnoMXZK2er2U+1ftLjgw50yPlYOJuoaEp40ui8QjOKgJnWumPZXGRY4MdoJ997KAtj42IgR0Z5h5jo0WWBsJZw7TNbz2AYYdY1H+ePvewyAtHLnyirUDxNGPNkRFiTpRpkzjLgtaIE2i5lrAoETjOR7InCeQI2K8+3WgtuFOO1tuh+JdUT/uY2LdnxYDvP5IK9Or0AEd828EtKFOc7aiHLwvQ4WJy4GuCIAQLGzuEo40NvH9pDWiIlRhVnyPbhZW8zC7/AFIzyz16S8QlpvaCTEvJuDNHSn2JeA+M3kEawol3OEB0m7JGsMwkXEM2S/fP5+Soj74fQUzr0POM6OUc7W7BykhLRklUS4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
