travis:
  secure:
    BINSTAR_TOKEN: A6D03RAFS8H9C2TkIAJrOH/zF+gc+8T9JXYpOr94lzmI/8rZK6OdOimufqgl5Und97BAKRRAv4OE3ero1iEHA1v8lQ1sU24FaTsfM1yEIEgdq6fFhk0jkX0c0YmaYisjPylvSpVElmty/6hSeuJRXQY4X/QsPFocJUNA1Fu/szxYxtnY8CmopfX3eVxqjGmb05mKGpdDX39ODX/GcO8rVyOIsDaAEuD24P3cmDU4KLluy7rm3s5G1pQVuAjQEfGNp9csyv7fwBzsBLcyR9WRzLyywLExxHjcY9Dx3GY3AH7c/ePY9a4lI0rpJLnT5AV/clSpPW6/ighVOfLc93XXKU1H8Gpy/yYAvhspkg6wfiLMB5/pPnHocFD2zvDXJSF+ln5TXADux3NIIEI3EUqei62DMdIJlGdwbN/vpM0GtiVaKnlcCKdiTPnZYRL/H6US1bZwnOG7T8gP2XLqSNd7tzT+13zgXe6zfeDdIpV6KKI/zZFY6mSCybG3yH4jajWqNIK8Aoho8mjt97eLGUxBurKPsV2SRUNMA3Pn5CD6rR/qLb/cpe4nIohkvacS/LLVBde5lqgBp2xQky1tlDuvdy+ewfYISTtsjnkXqQH3Jzx8mqMjjeVABnnOkf8jgnQPZDtd5lvds4yJM8UyUv89PyTtnFjHxxr16FHyy745zHw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
